# Generated by Django 4.2.3 on 2023-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincontent",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
